=== rajulkumar/cdn-definitions/schema.json
{
    "$id": "http://release-engineering.github.io/cdn-definitions/schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "absolute_path": {
            "pattern": "^/",
            "type": "string"
        },
        "arch": {
            "type": "string"
        },
        "arch_list": {
            "items": {
                "$ref": "#/definitions/arch"
            },
            "type": "array",
            "uniqueItems": true
        },
        "beta_and_ga_keys_mapping": {
            "additionalProperties": false,
            "properties": {
                "beta_keys": {
                    "$ref": "#/definitions/signing_key_list"
                },
                "ga_keys": {
                    "$ref": "#/definitions/signing_key_list"
                }
            },
            "required": [
                "ga_keys"
            ],
            "type": "object"
        },
        "cfme_version_mappings_list": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/major_or_release_version"
                }
            },
            "propertyNames": {
                "$ref": "#/definitions/major_or_release_version"
            },
            "type": "object"
        },
        "current_latest_rhel_versions": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "#/definitions/release_version"
                        }
                    ]
                }
            },
            "propertyNames": {
                "pattern": "^(current|latest)\\_rhel[0-9]+\\_(beta|dist)$",
                "type": "string"
            },
            "type": "object"
        },
        "env_to_releasever_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/current_latest_rhel_versions"
                }
            },
            "type": "object"
        },
        "exclude_versions_from_listings": {
            "items": {
                "$ref": "#/definitions/release_version"
            },
            "type": "array",
            "uniqueItems": true
        },
        "major_or_release_version": {
            "pattern": "^[0-9]+(\\.[0-9]+)*$",
            "type": "string"
        },
        "major_to_release_version_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/release_version"
                }
            },
            "propertyNames": {
                "$ref": "#/definitions/major_version_string"
            },
            "type": "object"
        },
        "major_version": {
            "type": "integer"
        },
        "major_version_list": {
            "items": {
                "$ref": "#/definitions/major_version"
            },
            "type": "array",
            "uniqueItems": true
        },
        "major_version_string": {
            "pattern": "^[0-9]+$",
            "type": "string"
        },
        "major_version_to_signing_keys_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/beta_and_ga_keys_mapping"
                }
            },
            "propertyNames": {
                "$ref": "#/definitions/major_version_string"
            }
        },
        "path_alias": {
            "additionalProperties": false,
            "properties": {
                "dest": {
                    "$ref": "#/definitions/absolute_path"
                },
                "src": {
                    "$ref": "#/definitions/absolute_path"
                }
            },
            "required": [
                "src",
                "dest"
            ],
            "type": "object"
        },
        "path_alias_list": {
            "items": {
                "$ref": "#/definitions/path_alias"
            },
            "type": "array",
            "uniqueItems": true
        },
        "product_id": {
            "pattern": "^[0-9]+$",
            "type": "string"
        },
        "product_id_list": {
            "items": {
                "$ref": "#/definitions/product_id"
            },
            "type": "array",
            "uniqueItems": true
        },
        "release_stream_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/release_version_list"
                }
            },
            "type": "object"
        },
        "release_version": {
            "pattern": "^[0-9]+\\.[0-9]+$",
            "type": "string"
        },
        "release_version_list": {
            "items": {
                "$ref": "#/definitions/release_version"
            },
            "type": "array",
            "uniqueItems": true
        },
        "signing_key": {
            "pattern": "^[A-F0-9]{8}$",
            "type": "string"
        },
        "signing_key_list": {
            "items": {
                "$ref": "#/definitions/signing_key"
            },
            "type": "array",
            "uniqueItems": true
        },
        "signing_keys_mapping": {
            "additionalProperties": false,
            "properties": {
                "default": {
                    "$ref": "#/definitions/beta_and_ga_keys_mapping"
                },
                "layered_product": {
                    "$ref": "#/definitions/string_to_signing_keys_mapping"
                },
                "major_version": {
                    "$ref": "#/definitions/major_version_to_signing_keys_mapping"
                },
                "platform": {
                    "$ref": "#/definitions/string_to_signing_keys_mapping"
                }
            },
            "required": [
                "layered_product",
                "platform",
                "major_version"
            ],
            "type": "object"
        },
        "string_to_signing_keys_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/beta_and_ga_keys_mapping"
                }
            }
        },
        "symlink_exception_list": {
            "items": {
                "$ref": "#/definitions/absolute_path"
            },
            "type": "array",
            "uniqueItems": true
        },
        "tps_variant_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "version_to_arch_list_mapping": {
            "additionalProperties": false,
            "patternProperties": {
                ".*": {
                    "$ref": "#/definitions/arch_list"
                }
            },
            "propertyNames": {
                "$ref": "#/definitions/major_version_string"
            },
            "type": "object"
        }
    },
    "properties": {
        "cfme_version_mappings": {
            "$ref": "#/definitions/cfme_version_mappings_list"
        },
        "env_to_releasever_mappings": {
            "$ref": "#/definitions/env_to_releasever_mapping"
        },
        "exclude_from_listings": {
            "$ref": "#/definitions/exclude_versions_from_listings"
        },
        "filter_arches_from_release": {
            "$ref": "#/definitions/version_to_arch_list_mapping"
        },
        "ignore_lp_version_product_ids": {
            "$ref": "#/definitions/product_id_list"
        },
        "origin_alias": {
            "$ref": "#/definitions/path_alias_list"
        },
        "override_initial_rhel_release": {
            "$ref": "#/definitions/major_to_release_version_mapping"
        },
        "populate_ubi_dot_repos": {
            "type": "boolean"
        },
        "release_stream_mappings": {
            "$ref": "#/definitions/release_stream_mapping"
        },
        "rhel_open_dist": {
            "$ref": "#/definitions/major_version_list"
        },
        "rhui_alias": {
            "$ref": "#/definitions/path_alias_list"
        },
        "rhui_product_id": {
            "$ref": "#/definitions/product_id"
        },
        "signing_keys_mappings": {
            "$ref": "#/definitions/signing_keys_mapping"
        },
        "symlink_exceptions": {
            "$ref": "#/definitions/symlink_exception_list"
        },
        "tps_variant_mappings": {
            "$ref": "#/definitions/tps_variant_mapping"
        },
        "version": {
            "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
            "type": "string"
        }
    },
    "type": "object"
}

=== rajulkumar/cdn-definitions/data.json
{
    "cfme_version_mappings": {
        "0.0": "0.0"
    },
    "env_to_releasever_mappings": {
        "prod": {
            "current_rhel0_beta": "0.0",
            "current_rhel0_dist": "0.0",
            "latest_rhel0_beta": "0.0",
            "latest_rhel0_dist": "0.0"
        },
        "qa": {
            "current_rhel0_beta": "0.0",
            "current_rhel0_dist": "0.0",
            "latest_rhel0_beta": "0.0",
            "latest_rhel0_dist": "0.0"
        },
        "stage": {
            "current_rhel0_beta": "0.0",
            "current_rhel0_dist": "0.0",
            "latest_rhel0_beta": "0.0",
            "latest_rhel0_dist": null
        }
    },
    "exclude_from_listings": [
        "0.0"
    ],
    "filter_arches_from_release": {
        "0": [
            "example_64"
        ]
    },
    "ignore_lp_version_product_ids": [
        "000"
    ],
    "origin_alias": [
        {
            "dest": "/origin",
            "src": "/content/origin"
        },
        {
            "dest": "/origin/rpms",
            "src": "/origin/rpm"
        }
    ],
    "override_initial_rhel_release": {
        "0": "0.0"
    },
    "populate_ubi_dot_repos": true,
    "release_stream_mappings": {
        "aus": [
            "0.0"
        ],
        "e4s": [
            "0.0"
        ],
        "eus": [
            "0.0"
        ],
        "other": [
            "0.0"
        ],
        "tus": [
            "0.0"
        ]
    },
    "rhel_open_dist": [
        0
    ],
    "rhui_alias": [
        {
            "dest": "/content/aus/rhel8",
            "src": "/content/aus/rhel8/rhui"
        },
        {
            "dest": "/content/aus/rhel",
            "src": "/content/aus/rhel/rhui"
        },
        {
            "dest": "/content/beta/rhel8",
            "src": "/content/beta/rhel8/rhui"
        },
        {
            "dest": "/content/beta/rhel-alt",
            "src": "/content/beta/rhel-alt/rhui"
        },
        {
            "dest": "/content/beta/rhel",
            "src": "/content/beta/rhel/rhui"
        },
        {
            "dest": "/content/beta/rhs",
            "src": "/content/beta/rhs/rhui"
        },
        {
            "dest": "/content/dist/layered",
            "src": "/content/dist/layered/rhui"
        },
        {
            "dest": "/content/dist/middleware",
            "src": "/content/dist/middleware/rhui"
        },
        {
            "dest": "/content/dist/rhel8",
            "src": "/content/dist/rhel8/rhui"
        },
        {
            "dest": "/content/dist/rhel-alt",
            "src": "/content/dist/rhel-alt/rhui"
        },
        {
            "dest": "/content/dist/rhel",
            "src": "/content/dist/rhel/rhui"
        },
        {
            "dest": "/content/dist/rhes",
            "src": "/content/dist/rhes/rhui"
        },
        {
            "dest": "/content/dist/rhs",
            "src": "/content/dist/rhs/rhui"
        },
        {
            "dest": "/content/e4s/rhel8",
            "src": "/content/e4s/rhel8/rhui"
        },
        {
            "dest": "/content/e4s/rhel",
            "src": "/content/e4s/rhel/rhui"
        },
        {
            "dest": "/content/els/rhel",
            "src": "/content/els/rhel/rhui"
        },
        {
            "dest": "/content/eus/rhel8",
            "src": "/content/eus/rhel8/rhui"
        },
        {
            "dest": "/content/eus/rhel",
            "src": "/content/eus/rhel/rhui"
        },
        {
            "dest": "/content/rc/rhel",
            "src": "/content/rc/rhel/rhui"
        }
    ],
    "rhui_product_id": "000",
    "signing_keys_mappings": {
        "default": {
            "beta_keys": [
                "BBBBBBBB"
            ],
            "ga_keys": [
                "00000000"
            ]
        },
        "layered_product": {
            "example-lp": {
                "ga_keys": [
                    "00000000"
                ]
            }
        },
        "major_version": {
            "0": {
                "beta_keys": [
                    "BBBBBBBB"
                ],
                "ga_keys": [
                    "00000000"
                ]
            }
        },
        "platform": {
            "example_none": {
                "ga_keys": []
            },
            "example_platform": {
                "beta_keys": [
                    "BBBBBBBB"
                ],
                "ga_keys": [
                    "FFFFFFFF"
                ]
            }
        }
    },
    "symlink_exceptions": [
        "/this/is/an/example/"
    ],
    "tps_variant_mappings": {
        "example-arch": "Example-Variant"
    },
    "version": "1.2.0"
}
